version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-scripts --no-interaction --prefer-dist
      - echo "Installing Sonar Scanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - sudo unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-cli-3.3.0.1492-linux/bin
      - echo "pre build stage completed" 
      - echo $PATH

  pre_build:
    commands:
      - echo "Running PHPStan static analysis..."

  build:
    commands:
      #- vendor/bin/phpstan analyse || true
      - echo " PHPStan static analysis COMPLETE..."
      - sonar-scanner -Dsonar.login=39c1bcd5efecccd9062f593ab1c93762462e676c -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=manidasari27_DoctorApp -Dsonar.organization=manidasari27 
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=manidasari27_DoctorApp >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
      #- mvn verify sonar:sonar -Dsonar.projectKey=manidasari27_DoctorApp -Dsonar.organization=manidasari27 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=39c1bcd5efecccd9062f593ab1c93762462e676c
      - echo "build stage completed"

reports:
  phpstan-report:
    files:
      - phpstan.log
    file-format: RAW
    base-directory: ./

artifacts:
  files:
    - "**/*"
