version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-scripts --no-interaction --prefer-dist

  pre_build:
    commands:
      - echo "Running PHPStan static analysis..."
      - ls 
      - echo "LS COMPLETE!!!!!"

  build:
    commands:
      - vendor/bin/phpstan analyse

reports:
  phpstan-report:
    files:
      - phpstan.log
    file-format: RAW
    base-directory: ./
